### ISSUE TITLE
Add Readme files.

### ISSUE THREAD

**Issue by UzairHussain193** [UzairHussain193/Get_Start_with_OpenSource_Contributions#28]
Add readme of folders in which it is missing.

**Comment by kedarnathrothe** [comment]
Please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Mayurghule2** [comment]
hey could you please assign this task , i want to contribute

**Comment by anushka9555** [comment]
please assign me
