### ISSUE TITLE
errors in html files

### ISSUE THREAD

**Issue by UzairHussain193** [UzairHussain193/Get_Start_with_OpenSource_Contributions#29]
Review thoroughly the folder of Html_css and javascript and check all the tasks have been completed. And the tasks are done as defined, if you find any errors or bugs, resolve it.

**Comment by akshat209141** [comment]
I can do it sir, please assign me this with hactoberfest tag.

**Comment by UzairHussain193** [comment]
I have assigned this task to you.

**Comment by varunpareek690** [comment]
Hi sir, I have already contributed to some extent and I intend to do the full project , so I request you to please assign this PR to me under the label of " HACKTOBERFEST-ACCEPTED " or "HACTOBERFEST" , You may review my work done as I have already commited some changes
Thank you!

**Comment by UzairHussain193** [comment]
I have assigned you a pull request and merged it.
