### ISSUE TITLE
An email validator and an email slicer in Python

### ISSUE THREAD

**Issue by Maryam0330** [UzairHussain193/Get_Start_with_OpenSource_Contributions#31]
I am writing to propose a contribution to the python project. I have developed two Python projects: an email validator and an email slicer.
The email validator checks if an email address is valid. The email slicer extracts the username and domain from an email address.
I believe that these projects would be a valuable addition to the python project. They would make it easier for users to validate email addresses and extract information from email addresses.

**Comment by UzairHussain193** [comment]
Yeah you can contribute both projects in a seperate folder in this repo, and make sure to add readme file in that folder that will help viewers to understand your project.
Keep contributing.

**Comment by UzairHussain193** [comment]
Okay, I have merged your pull request.

**Comment by Maryam0330** [comment]
Thank you!
