### ISSUE TITLE
Create Median of 2 sorted Arrays in CPP

### ISSUE THREAD

**Issue by shashank-lol** [UzairHussain193/Get_Start_with_OpenSource_Contributions#41]
Please assign this to me under hacktober fest.

**Comment by UzairHussain193** [comment]
I am assigning you but before this please let me know how you are going to contrbute in this issue?

**Comment by shashank-lol** [comment]
I have added a pull request for the following code in C++.

**Comment by akshat209141** [comment]
[median.txt](https://github.com/UzairHussain193/Get_Start_with_OpenSource_Contributions/files/12837582/median.txt)

**Comment by akshat209141** [comment]
[median.txt](https://github.com/UzairHussain193/Get_Start_with_OpenSource_Contributions/files/12837600/median.txt)

**Comment by akshat209141** [comment]
# #https://github.com/UzairHussain193/Get_Start_with_OpenSource_Contributions/files/12837600/median.txt

**Comment by akshat209141** [comment]
i have added the pull request please merge it

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task
