### ISSUE TITLE
I can create a simple BMi calculator using HTML CSS javascript

### ISSUE THREAD

**Issue by SajithMinrutha** [UzairHussain193/Get_Start_with_OpenSource_Contributions#69]
This project is about manipulating DOM in java script

**Comment by SajithMinrutha** [comment]
please assign it to me under hacktoberfest2023

**Comment by SajithMinrutha** [comment]
please review and merge the PR

**Comment by SajithMinrutha** [comment]
please review and merge the PR

**Comment by SajithMinrutha** [comment]
@UzairHussain193 please review the pr

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me under hactoberfest
